### ISSUE TITLE
mozzle cli not available

### ISSUE THREAD

**Issue by gnusshall** [Bo0mer/mozzle#14]
hi,

i am not sure if i missed something somewhere in the instructions. after cloning the repo and successfully provision the vagrant container i am not able to find the mozzle command inside and outside the container. would you be so kind to give me a hint?

thanks!

br
gernot

**Comment by Bo0mer** [comment]
Hi,

You can obtain the mozzle cli in two ways. 

1. Download the binary from the releases page - https://github.com/Bo0mer/mozzle/releases. Make sure to choose the right one for your platform
2. Build it. You will need Go installed on your system. Then, after going to the root of the repo just run 'go install ./...'

If you're new to Go option 1 is way easier. 

Please let me know if there are any more issues. 
I'll also update the vagrant box to supply the executable there as well. 

Regards,
Ivan

**Comment by Bo0mer** [comment]
Also, if you choose to download from the releases page, please make sure you checkout commit 3842f007ea61dcf1e0ae2d12d0bffa634f7bda10 and reprovision the vagrant box by running:
"vagrant destroy && vagrant provision" from the mib folder. 

This is necessary because there are changes to the Grafana dashboards since the last release, but the mozzle cli lacks a new release, which I plan to do in the upcoming week.

Regards,
Ivan

**Comment by gnusshall** [comment]
Thanks! Now it is working. I didn´t download the binary from the release page...

br,
Gernot

**Comment by vishalchds** [comment]
I tried installing the binary file for my os .. it shows up "mozzle: error occured during Monitor: doing info request failed: Get https://api.bosh-lite.com/v2/info: net/http: request cancelled while waiting for connection
